# Site settings
title: Holly Braun
email: hbraun25@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I graduated from BYU in elementary education. Now I teach five students, my
  daughters and my sons. I'm passionate about math, minecraft, soccer, and biking. Allow me to share my thoughts with you!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hollybraun.com" # the base hostname & protocol for your site
twitter_username: hbraun25
github_username:  hollyadele
include: ["_pages"]

# Build settings
markdown: kramdown
